name: Déploiement GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Vérifier la structure des fichiers (optionnel mais pratique pour debug)
      - name: Lister les fichiers
        run: ls -R

      # 3️⃣ Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            personal_token: ${{ secrets.GH_PAT }}
            publish_dir: ./src
            publish_branch: gh-pages
            force_orphan: true
            keep_files: false
            enable_jekyll: false
            allow_empty_commit: false
            disable_nojekyll: false
            exclude_assets: .github
    
